### ISSUE TITLE
Escaping User Input

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw_editor#2]
Consider the following scenario:

    A malicious user edits a spec_items and enters some dangerous js code in a text field
    After editing has been completed, the text field is rendered as html
    When the text field is rendered as html, the malicious js code is executed and the security of the host is compromised

I understand that Django uses various escaping mechanisms to sanitize potentially dangerous user inputs. In some cases, though, I need to by-pass these mechanisms (e.g. in the rendering of item_ver_links in list_spec_items.html) by marking an output as 'safe' (in reality. since part of this output comes from the user, I cannot be sure that it is safe).

It is not clear to me whether this creates a security risk.

**Potential Solution** 
Given that:

(a) the problem is that users might input malicious code, and
(b) users input text when they edit a spec_item through the SpecItemForm,

The simplest solution might be to escape all strings entered by the user through SpecItemForm. This could be done by using the predefined django function escape(). If XYZ is a text spec_iten text field, the escape() function should be called by the clean_XYZ functions in SpecItemForm.

**Comment by PStump** [comment]
If I understand this issue correctly, it is about cleaning user input to then create html output again.

[Bleach](https://bleach.readthedocs.io/en/latest/index.html) should do the job. (There is also a django module for this [django-bleach](https://bitbucket.org/ionata/django-bleach/src/master/).)

> Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes.

**Comment by pasetti** [comment]
The situation is as follows:

> The Django infrastructure ensures that items rendered in HTML through Django templates are sanitized (there is an implicit call to the escape() function on text fields displayed in HTML)
> We only render HTML through Django templates
> In some cases, we need to inject HTML code into our displays. This is notably the case when we create hyperlinks. In these cases, we mark these fields as "safe" (or else our HTML tags would be escaped)

The danger then is that a user might inject malicious code in a field to which we add HTML code: since such a field is marked as safe, the malicious code would get through to the HTML page. 

The solution to this problem is that, before adding HTML code to a field, we escape its content. This makes is safe to mark it as "safe".
