### ISSUE TITLE
Login label on the main page

### ISSUE THREAD

**Issue by cechticky** [pnp-software/cordetfw_editor#50]
There are two "Login" labels, do we need both? What would happen if we remove the bold one on the top?
![image](https://user-images.githubusercontent.com/5507223/131997266-b745e12f-403a-45d2-9974-c10f1a186d97.png)

**Comment by PStump** [comment]
You are right, it does not make sense to have `Login` in the header.
I would exchange this bold one with `Sign-In`.

**Comment by pasetti** [comment]
I have replaced the "Login" at the top with "Sign-In". I have also taken this opportunity to update the short description of the project in the log-in page.

**Comment by PStump** [comment]
Fixed by Alessandro with https://github.com/pnp-software/cordetfw_editor/commit/c509676d8b8e39ae57e1d1e86fa18e6b100fb
