### ISSUE TITLE
Migration to Bootstrap 5

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw_editor#60]
In the company teleconference on 7 January, it was agreed that the front-end of the editor would be migrated to Bootstrap 5. This task is **urgent** because its completion is a pre-condition for several other tickets affecting the front-end.

**Comment by PStump** [comment]
This comment should act as a updated work in progress list, to align between the team members.
Please edit this comment if you work on any item. (Change the order of the items to prioritize.)

- [ ] create `base_bootstrap5.html` (in work by Pascal)
- [ ] update `index.html` to use bootstrap5 (in work by Pascal)
- [ ] update `index_top.html` to use bootstrap5
- [ ] update `edit_project.html` to use bootstrap5
- [ ] update `list_spec_items.html` to use bootstrap5
- [ ] update `basic_form.html` to use bootstrap5
- [ ] update `make_release.html` to use bootstrap5
- [ ] update `upload_file.html` to use bootstrap5
- [ ] update `help.html` to use bootstrap5
- [ ] update `lockout.html` to use bootstrap5
- [ ] remove `base_generic.html` & `base_generic_old.html`
- [ ] rename `base_bootstrap5.html` to `base_generic.html`

**Comment by pasetti** [comment]
I checked the update of the index and it looks fine to me (I made a few minor changes to the tool tips and to the arrangement of the title in the login page).

If possible, I would like to ask Pascal to update the list_spec_item page next because this is the one where I need to make some changes for some pending tickets.

One last point: I see that there is a kind of "blue theme". I assume that the blue colour is some kind of default. If we wanted to change it, would we have to change each element or can the change be done in some central location?

**Comment by pasetti** [comment]
I have one comment concerning the bootstrap5 version of the list_spec_item page. I notice that if I make the browser window wider, the content in the window remains in the middle of the window and there is lots of blank space in the left and right of the window (see the screenshot below). This unused space does not seem very efficient. Is there a way to have the text in the window expand with the browser window?  

![image](https://user-images.githubusercontent.com/15838404/155893273-a3556006-e755-47cb-98e0-0ab5da5df0f3.png)

**Comment by cechticky** [comment]
I believe this shall be possible, because bootstrap is about responsive layout
https://getbootstrap.com/docs/5.1/layout/grid/

I'll look into this in detail.

**Comment by PStump** [comment]
Currently the class `container` is used (max-with 1320px) but could be easily changed to `container-fluid`.
Is this expected only for the table or also for the header/footer?

**Comment by PStump** [comment]
example (with `container-fluid`) for only the list_spect_items pushed to master

**Comment by pasetti** [comment]
I checked the list_spec_items with the `container-fluid` and I confirm it has the desired effect that the table expands to follow changes in the window width. Just one comment (with apologies for being so picky): the margin on the left and right sides of the window is very narrow. Can we have a bit wider (but not much more -- we need lots of space for the lists).

> Is this expected only for the table or also for the header/footer?

I think that we should also have it for the header/footer

One last point: I think that we only need this effect for the list of items. In other cases (e.g. the index or the forms where we enter data), I believe that we can keep things as they are.

**Comment by PStump** [comment]
The templates are moved to bootstrap 5, therefore I will close this issue.
I suggest to open new issues for every problem or change request.
