### ISSUE TITLE
add user to R/W or R/O if user exists

### ISSUE THREAD

**Issue by PStump** [pnp-software/cordetfw_editor#66]
If a user already exists as R/W or R/O in a project, it is not possible to add the user to R/O or R/W without deleting the user first from the list.
I think it would be convenient to choose the user from the dropdown directly instead having to search if the user already has some access to the project.

**Comment by pasetti** [comment]
I have implemented a simple fix: you can now select a user who is already allocated and, if its specified role is different from its current role, the user role is updated.
The change has been checked in the main branch (but not yet uploaded to the live server).

**Comment by PStump** [comment]
perfect :+1:
