### ISSUE TITLE
Template for Forms

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw_editor#74]
The "Edit Application" form has a few fields which are presented to the user one after the other. A few days ago, I wanted to change the widget for the "Categories" field from being a plain `CharField` to being a `CharField` with a text area (so as to allow the entry box to extend over more than one line). I made what I thought was the obvious change in `forms.py` from this form:

```
    description = forms.CharField(widget=forms.Textarea)
    cats = forms.CharField()

```
to this form:

```
    description = forms.CharField(widget=forms.Textarea)
    cats = forms.CharField(widget=forms.Textarea)

```
But this change failed to work (in fact, it disabled the entire form). After some investigation, I realized that the problem lies in the `template application_form.html `which somehow also encodes the type of input field. I tried to make the change in the template but (as is often the case when I attempt something on the front end side), I failed abysmally. 

I know that we deliberately moved away from the `crispy` approach for forms but I would like to ask whether what we have now is the only alternative or whether it is possible to have some middle way where we avoid delegating everything to `crispy` but also avoiding having such a tight coupling between the form definition in `forms.py` and the template. Now, if we change the name of a form label, or if we want to add a new label, or if we want to change the widget associated to a form field, we must implement the change both in `forms.py` and in the template and the two changes must be very carefully coordinated. Can anything be done to lessen this dependency?

**Comment by pasetti** [comment]
First of all: congratulations! This looks to me like a brilliant solution ...

I re-open this issue, because I have a problem which *might* be due to the new form approach. When I edit a spec_item, I always get an exception owing to #Column 'n1' cannot be null". The error is reported even if I do not make any changes to the spec_item. The error occurs on spec_item which I was able to edit without problems and it must therefore be due to a recent change.

The issue is that field 'n1' is one of the integer fields of spec_items. Its default value is zero. In most cases, it is not part of a spec_item and therefore it should remain unchanged but, apparently, the form assigns to it a value of 'None', which triggers an exception.

If the problem is not clear, we can discuss the matter by telephone.

**Comment by pasetti** [comment]
I think that I now understand what the problem is. With the old forms, the html with was generated by the Django template language included the following line:

<input type="hidden" id="id_n1" name="n1" value="0">

Here, the value of zero corresponds to the default value for the n1 field as it is defined in the Django database model (file `model.py`). With the new form, the html code for the n1 field looks like this:

<input type="hidden" id="id_n1" name="n1">

Now, no value for n1 is defined and hence the Django infrastructure uses "None" as a value for n1 and this triggers the exception. In the `generic_form_field.html` template, this input tag comes from the following code:

```
{% if field.widget_type == "hidden" %}
<input type="hidden" id="{{ field.id_for_label }}" name="{{ field.html_name }}">
{% endif %}
```

Is there any way to extend the template to add a "value" for the input which corresponds to the default value defined in `model.py`?

**Comment by PStump** [comment]
should be fixed with https://github.com/pnp-software/cordetfw_editor/commit/117b4be885aff1bd6215a5631de7bb4dde135438

**Comment by pasetti** [comment]
Yes, thanks. Now it works.
