### ISSUE TITLE
Undoing of Changes & Visibility over Deleted Items

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw_editor#9]
We should consider a mechanism whereby the last change of a specification item is undone (for instance: the user calls up the history of a specification item and, if the status of the spec_item, is MOD, the user has the option to undo the modification.

A related issue concerns specification items which have been deleted. These are currently invisible but we should introduce a mechanism to display them and, if desired, to undo the deletion.

**Comment by pasetti** [comment]
Here are some possible solutions:
- In the spec_item list, spec_items which are MOD are shown in red and if the user checks their history, there is an option to undo the change and bring them back to CNF status
- In the spec_item list, spec_items which have been deleted after the last release are shown as greyed-out items, the copy and split buttons are omitted and the edit button is replaced with an 'undelete' button

For the first bullet: maybe there is no need to show them in red font; it is up to the user to select the 'status' among the fields to be displayed. Or we could have a side-bar at the left or we could just make the domain:name red to have a less obtrusive way of identifying changed fields.

**Comment by pasetti** [comment]
A spec_item has a 'status' which is one of: NEW, MOD (modified), CNF (confirmed), OBS (obsolete) and DEL (deleted). When we list spec_items, it might be interesting to see their status. Since the 'status' is an attribute of a spec_item, users can configure the tool to list the status (just as they can configure the tool to list any other spec_item attribute). Another option however would be to use some visual marking to identify the status of a spec_item. For instance:

- We could have a side bar for MOD spec_items to identify them as 'modified'
- We could list spec_items which are in DEL status in grayed-out font
- We could use different font or background colours for different statuses
- We could use a small icon attached to each list row to identify the status
-  . . . 

I am assigning the ticket to Pascal just in case he has any ideas/recommendations on this issue.

**Comment by PStump** [comment]
partially implemented in 360779ed82cc7ec60cf62c3c4006f3e765f2c5de

**Comment by pasetti** [comment]
I have the new feature and I can see that, if I make a change to a CNF item (thus changing its status to MOD), the "history" icon (the little clock) becomes red. This is fine from a functional point of view but the change in colour is difficult to detect because the icon is mostly white text (by contrast, the fact that the "delete" icon is red is clearly visible). Is it possible to have a different "history" icon where the change in colour is more apparent?

**Comment by PStump** [comment]
> Is it possible to have a different "history" icon where the change in color is more apparent?

Sure. You can use any Icon listed here: https://icons.getbootstrap.com/
For the moment I have changed it to `clock-fill`, but feel free to have a look into the icon list (also for the other icons, maybe you find better suitable ones).

**Comment by pasetti** [comment]
Clock-fill is fine.... and thanks for the pointer to the bootstrap icons!

**Comment by pasetti** [comment]
This issue also covered the issue of undoing deletions. I now no longer think that we should support this capability: suppose that we have spec item S1 which is a modified version of spec item S2 (i.e. S2 has status "obsolete"). There may be other spec items which reference S1 and, if delete S1, the links will become broken.
