### ISSUE TITLE
Spec_Item History Lost With Pagination 

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw_editor#90]
The pagination mechanism has been recently introduced in the editor. It works fine but I just noticed that we no longer have the history of a specification item.

NB: I am not quite sure that this bug is due to the pagination mechanism but I know that the history mechanism was working on 30 Dec 2022 when I did release 1.5.0 of the TEPI Editor and it does not seem to be working now. Hence, I suspect that the culprit is the pagination mechanism.

**Comment by PStump** [comment]
Yes problem started with adding of the pagination mechanism, I have not realized that the same template is used for the history view.
